<template><div class="joint-panel" data-testid="joint-controls"><div class="joint-panel-tools"><el-input v-model="query" size="small" clearable placeholder="搜索关节"/><el-select v-model="filter" size="small"><el-option label="全部" value="all"/><el-option label="Revolute" value="revolute"/><el-option label="Continuous" value="continuous"/><el-option label="Prismatic" value="prismatic"/></el-select><el-select v-model="rotationUnit" size="small" data-testid="rotation-unit"><el-option label="rad" value="rad"/><el-option label="deg" value="deg"/></el-select><el-select v-model="translationUnit" size="small"><el-option label="m" value="m"/><el-option label="cm" value="cm"/><el-option label="mm" value="mm"/></el-select><el-select v-model="precision" size="small"><el-option v-for="n in [3,4,6]" :key="n" :label="`${n} 位`" :value="n"/></el-select><el-button size="small" @click="savePose">保存姿态</el-button><el-select v-model="selectedPose" size="small" placeholder="已存姿态"><el-option v-for="pose in poses" :key="pose.name" :label="pose.name" :value="pose.name"/></el-select><el-button size="small" :disabled="!selectedPose" @click="loadPose">加载</el-button><el-button size="small" @click="zeroPose">全部归零</el-button></div><div class="joint-controls"><div v-if="!filtered.length" class="dock-empty">没有匹配的关节</div><JointSlider v-for="joint in filtered" :key="joint.id" :joint="joint" :value="store.jointValues[joint.id]??0" :rotation-unit="rotationUnit" :translation-unit="translationUnit" :precision="precision" @preview="store.previewJoint" @commit="store.queueJointCommit" /></div></div></template>
<script setup lang="ts">
import {computed,ref} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import {useEditorStore} from '@/stores/editor';import JointSlider from './JointSlider.vue';import type {RotationUnit,TranslationUnit} from './JointValueInput.vue';
interface Pose{name:string;values:Record<string,number>}
const store=useEditorStore(),query=ref(''),filter=ref('all'),rotationUnit=ref<RotationUnit>('rad'),translationUnit=ref<TranslationUnit>('m'),precision=ref(3),selectedPose=ref('');const storageKey='morphology-studio.joint-poses';const poses=ref<Pose[]>(readPoses());
const filtered=computed(()=>store.scene.joints.filter(j=>!['fixed','planar','floating'].includes(j.type)&&(filter.value==='all'||j.type===filter.value)&&j.name.toLowerCase().includes(query.value.toLowerCase())));
function readPoses(){try{return JSON.parse(localStorage.getItem(storageKey)||'[]') as Pose[]}catch{return[]}}
async function savePose(){const {value:name}=await ElMessageBox.prompt('输入姿态名称','保存姿态',{inputPattern:/\S+/,inputErrorMessage:'姿态名称不能为空'});const values=Object.fromEntries(store.scene.joints.filter(j=>!['fixed','planar','floating'].includes(j.type)).map(j=>[j.id,store.jointValues[j.id]??0]));poses.value=poses.value.filter(p=>p.name!==name).concat({name,values});localStorage.setItem(storageKey,JSON.stringify(poses.value));selectedPose.value=name;ElMessage.success('姿态已保存')}
async function loadPose(){const pose=poses.value.find(p=>p.name===selectedPose.value);if(!pose)return;await store.commitJointPose(pose.values);ElMessage.success(`已加载姿态：${pose.name}`)}
async function zeroPose(){const values=Object.fromEntries(store.scene.joints.filter(j=>!['fixed','planar','floating'].includes(j.type)).map(j=>[j.id,0]));await store.commitJointPose(values)}
</script>
<style scoped>.joint-panel{height:calc(100% - 36px);display:flex;min-height:0;flex-direction:column}.joint-panel-tools{display:grid;grid-template-columns:minmax(120px,1fr) 112px 74px 74px 74px auto 120px auto auto;gap:6px;padding:6px 16px;border-bottom:1px solid #253542}.joint-controls{flex:1;min-height:0;overflow:auto;padding:6px 16px}.joint-controls :deep(.joint-row){padding:3px}@media(max-width:1280px){.joint-panel-tools{grid-template-columns:minmax(120px,1fr) repeat(4,74px) auto auto}.joint-panel-tools>*:nth-last-child(-n+3){display:none}}</style>
