source: models/robotis_hand/robotis_hand_description/urdf/hx5_d20_rev2/hx5_d20_right.xacro
mode: assisted
arguments:
  prefix: ""
  use_sim: "false"
  use_mock_hardware: "false"
  mock_sensor_commands: "false"
package_map: configs/package_maps/local_models.yaml
