<template><section class="precise-transform" data-testid="transform-inspector"><div class="edit-target"><b>编辑目标</b><span>{{targetLabel}}</span><small v-if="parentJoint">父 Joint：{{parentJoint.name}} · 父 Link：{{parentJoint.parent}}</small></div><div class="transform-options"><el-select v-model="translationUnit" aria-label="平移单位"><el-option label="m" value="m"/><el-option label="cm" value="cm"/><el-option label="mm" value="mm"/></el-select><el-select v-model="rotationUnit" aria-label="旋转单位"><el-option label="deg" value="deg"/><el-option label="rad" value="rad"/></el-select><el-select v-model="space" aria-label="坐标空间"><el-option label="Parent" value="parent"/><el-option label="Local" value="local"/><el-option label="World" value="world" disabled/></el-select></div><h4>XYZ <small>{{translationUnit}}</small></h4><div class="numeric-grid"><label v-for="(label,i) in ['X','Y','Z']" :key="label">{{label}}<el-input-number :data-testid="`xyz-${i}`" :model-value="displayXyz(i)" :step="translationStep" :controls="true" @update:model-value="setXyz(i,$event)"/></label></div><h4>RPY <small>{{rotationUnit}}</small></h4><div class="numeric-grid"><label v-for="(label,i) in ['Roll','Pitch','Yaw']" :key="label">{{label}}<el-input-number :data-testid="`rpy-${i}`" :model-value="displayRpy(i)" :step="rotationStep" :controls="true" @update:model-value="setRpy(i,$event)"/></label></div><h4>Quaternion <small>X Y Z W</small></h4><div class="quaternion-grid"><label v-for="(label,i) in ['X','Y','Z','W']" :key="label">{{label}}<el-input-number :data-testid="`quaternion-${i}`" v-model="quaternion[i]" :step="0.001" :controls="false" @change="quaternionChanged"/></label></div><p v-if="error" class="error">{{error}}</p><div class="transform-actions"><el-button size="small" @click="copy">复制</el-button><el-button size="small" @click="paste">粘贴</el-button><el-button size="small" @click="reset">重置</el-button><el-button size="small" @click="cancel">取消</el-button><el-button data-testid="apply-transform" size="small" type="primary" :disabled="!dirty||!!error" @click="apply">应用</el-button></div></section></template>
<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,reactive,ref,watch} from 'vue';import {ElMessage} from 'element-plus';import * as THREE from 'three';import {useEditorStore} from '@/stores/editor';import type {EditableTransform,TransformTarget} from '@/api/transforms';import type {JointNode} from '@/types/scene'
const store=useEditorStore(),draft=reactive<EditableTransform>({xyz:[0,0,0],rpy:[0,0,0]}),original=reactive<EditableTransform>({xyz:[0,0,0],rpy:[0,0,0]}),quaternion=reactive([0,0,0,1]),translationUnit=ref<'m'|'cm'|'mm'>('mm'),rotationUnit=ref<'deg'|'rad'>('deg'),space=ref<'parent'|'local'|'world'>('parent'),dirty=ref(false),error=ref('')
const parentJoint=computed(()=>store.selectedType==='link'?store.scene.joints.find(j=>j.child===store.selectedId):undefined),isRootLink=computed(()=>store.selectedType==='link'&&store.scene.rootLinks.includes(store.selectedId||'')),targetLabel=computed(()=>isRootLink.value?'模型实例变换':parentJoint.value?`${parentJoint.value.name}.origin`:store.selectedType==='joint'?`${store.selectedId}.origin`:store.selectedType==='visual'||store.selectedType==='collision'?`${store.selectedId}.origin`:store.selectedType||'未知')
const target=computed<{type:TransformTarget,id:string}|null>(()=>!store.selectedId?null:isRootLink.value?{type:'model_instance',id:store.scene.robotId!}:{type:store.selectedType as TransformTarget,id:store.selectedId})
function current():EditableTransform{if(isRootLink.value||store.selectedType==='model_instance')return store.scene.rootTransform;const j=store.selectedType==='joint'||store.selectedType==='assembly_connection'?store.scene.joints.find(x=>x.id===store.selectedId):parentJoint.value;if(j)return j.origin;for(const l of store.scene.links){const v=l.visuals.find(x=>x.id===store.selectedId);if(v)return{...v.origin,scale:v.scale}}return{xyz:[0,0,0],rpy:[0,0,0]}}
function rpyToQuaternion(){const q=new THREE.Quaternion().setFromEuler(new THREE.Euler(...draft.rpy as [number,number,number],'XYZ'));quaternion.splice(0,4,q.x,q.y,q.z,q.w)}function sync(){const v=current();draft.xyz=[...v.xyz];draft.rpy=[...v.rpy];draft.scale=v.scale?[...v.scale]:undefined;original.xyz=[...draft.xyz];original.rpy=[...draft.rpy];original.scale=draft.scale&&[...draft.scale];rpyToQuaternion();dirty.value=false;error.value=''}
const positionFactor=computed(()=>translationUnit.value==='m'?1:translationUnit.value==='cm'?100:1000),translationStep=computed(()=>translationUnit.value==='m'?.001:translationUnit.value==='cm'?.1:1),rotationStep=computed(()=>rotationUnit.value==='deg'?1:Math.PI/180)
function displayXyz(i:number){return draft.xyz[i]*positionFactor.value}function displayRpy(i:number){return rotationUnit.value==='deg'?THREE.MathUtils.radToDeg(draft.rpy[i]):draft.rpy[i]}function preview(){dirty.value=true;error.value=[...draft.xyz,...draft.rpy].every(Number.isFinite)?'':'请输入有限数值';if(!error.value)window.dispatchEvent(new CustomEvent('morphology-transform-preview',{detail:{target:target.value,transform:{xyz:[...draft.xyz],rpy:[...draft.rpy],scale:draft.scale&&[...draft.scale]}}}))}function setXyz(i:number,value:number|undefined){if(value===undefined)return;draft.xyz[i]=value/positionFactor.value;preview()}function setRpy(i:number,value:number|undefined){if(value===undefined)return;draft.rpy[i]=rotationUnit.value==='deg'?THREE.MathUtils.degToRad(value):value;rpyToQuaternion();preview()}function quaternionChanged(){const q=new THREE.Quaternion(...quaternion as [number,number,number,number]);if(![q.x,q.y,q.z,q.w].every(Number.isFinite)||q.lengthSq()<1e-12){error.value='四元数长度必须大于 0 且全部为有限数值';return}q.normalize();quaternion.splice(0,4,q.x,q.y,q.z,q.w);const e=new THREE.Euler().setFromQuaternion(q,'XYZ');draft.rpy=[e.x,e.y,e.z];preview()}
async function apply(){if(!target.value||error.value)return;await store.commit(target.value.type,target.value.id,{xyz:[...draft.xyz],rpy:[...draft.rpy],scale:draft.scale&&[...draft.scale]});ElMessage.success('变换已更新')}
function cancel(){draft.xyz=[...original.xyz];draft.rpy=[...original.rpy];draft.scale=original.scale&&[...original.scale];rpyToQuaternion();preview();dirty.value=false}function reset(){draft.xyz=[0,0,0];draft.rpy=[0,0,0];if(draft.scale)draft.scale=[1,1,1];rpyToQuaternion();preview()}
function payload(){return{type:'morphology-transform',space:space.value,xyz:[...draft.xyz],rpy:[...draft.rpy],quaternion:[...quaternion],scale:draft.scale&&[...draft.scale]}}async function copy(){const text=JSON.stringify(payload());localStorage.setItem('morphology-transform',text);await navigator.clipboard?.writeText(text).catch(()=>{});ElMessage.success('变换已复制')}async function paste(){try{const text=await navigator.clipboard?.readText().catch(()=>localStorage.getItem('morphology-transform')||'')||localStorage.getItem('morphology-transform')||'';const value=JSON.parse(text);if(value.type!=='morphology-transform'||!Array.isArray(value.xyz)||!Array.isArray(value.rpy))throw new Error('剪贴板不是 Morphology Transform');draft.xyz=value.xyz.map(Number);draft.rpy=value.rpy.map(Number);draft.scale=value.scale?.map(Number);rpyToQuaternion();preview()}catch(e){ElMessage.error(String(e))}}
function command(event:Event){const id=(event as CustomEvent).detail;if(id==='edit.copyTransform')void copy();if(id==='edit.pasteTransform')void paste();if(id==='edit.resetTransform')reset()}
watch(()=>[store.selectedType,store.selectedId,store.scene.revision],sync,{immediate:true});onMounted(()=>window.addEventListener('morphology-command',command));onBeforeUnmount(()=>window.removeEventListener('morphology-command',command))
</script>
<style scoped>.precise-transform{display:grid;gap:9px}.edit-target{display:flex;flex-direction:column;padding:8px;background:#172633;border-left:2px solid #31a8ed}.edit-target span{color:#d2e2ed}.edit-target small{color:#6f899c}.transform-options{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.precise-transform h4{margin:3px 0;color:#9db2c1}.precise-transform h4 small{float:right;color:#627b8d}.numeric-grid,.quaternion-grid{display:grid;grid-template-columns:1fr;gap:5px}.numeric-grid label,.quaternion-grid label{display:grid;grid-template-columns:42px minmax(0,1fr);align-items:center}.transform-actions{display:flex;flex-wrap:wrap;gap:5px}.error{color:#ef7373;font-size:11px}.precise-transform :deep(.el-input-number){width:100%}</style>
