<template>
 <section class="viewport" data-testid="robot-viewport">
  <div class="viewport-tools" data-testid="transform-toolbar">
   <button title="选择 (Q)" @click="store.clearSelection()">Q</button>
   <button :class="{active:store.transformMode==='translate'}" @click="store.transformMode='translate'">移动 W</button>
   <button :class="{active:store.transformMode==='rotate'}" @click="store.transformMode='rotate'">旋转 E</button>
   <button :class="{active:store.transformMode==='scale'}" @click="store.transformMode='scale'">缩放 R</button>
   <button @click="store.transformSpace=store.transformSpace==='local'?'world':'local'">{{store.transformSpace==='local'?'局部':'世界'}} X</button>
   <button @click="store.snapEnabled=!store.snapEnabled">吸附 {{store.snapEnabled?'开':'关'}}</button>
   <button @click="store.selectionLevel=store.selectionLevel==='link'?'geometry':'link'">{{store.selectionLevel==='link'?'Link 级':'几何级'}}</button>
   <button @click="store.editSemantic=store.editSemantic==='assembly'?'kinematic':'assembly'">{{store.editSemantic==='assembly'?'装配编辑':'运动学编辑'}}</button>
   <button @click="fitView">聚焦 F</button><span>{{store.scene.robotId || '空场景'}}</span>
  </div>
  <div ref="container" class="canvas-host"></div>
  <div v-if="!store.scene.robotId" class="viewport-empty"><div class="empty-orbit">⌁</div><h2>三维机器人工作区</h2><p>导入 URDF、Xacro 或 MJCF 模型开始编辑</p><el-button type="primary" @click="openPicker">选择模型文件</el-button></div>
  <div class="viewport-hint">单击选择 · W移动 · E旋转 · R缩放 · X局部/世界 · Ctrl+Z撤销</div>
 </section>
</template>
<script setup lang="ts">
import {onBeforeUnmount,onMounted,ref,watch} from 'vue';import * as THREE from 'three';import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';import {TransformControls} from 'three/examples/jsm/controls/TransformControls.js';import {STLLoader} from 'three/examples/jsm/loaders/STLLoader.js';import {ColladaLoader} from 'three/examples/jsm/loaders/ColladaLoader.js';import {useEditorStore} from '@/stores/editor';import {pickPath} from '@/api/models';import type {TransformTarget} from '@/api/transforms'
const store=useEditorStore(),container=ref<HTMLElement>();let renderer:THREE.WebGLRenderer,scene:THREE.Scene,camera:THREE.PerspectiveCamera,orbit:OrbitControls,gizmo:TransformControls,robotGroup:THREE.Group|undefined,outline:THREE.BoxHelper|undefined,frame=0;const objects=new Map<string,THREE.Object3D>(),proxy=new THREE.Object3D();let dragging=false,selectedParentWorld=new THREE.Matrix4(),down=new THREE.Vector2()
const rotation=(r:number[])=>new THREE.Matrix4().makeRotationZ(r[2]||0).multiply(new THREE.Matrix4().makeRotationY(r[1]||0)).multiply(new THREE.Matrix4().makeRotationX(r[0]||0));const matrix=(p:number[],r:number[])=>new THREE.Matrix4().makeTranslation(...p as [number,number,number]).multiply(rotation(r));
function apply(o:THREE.Object3D,p:number[],r:number[]){o.position.set(...p as [number,number,number]);o.quaternion.setFromRotationMatrix(rotation(r))}
function fallback(s:number[],i:number){return new THREE.Mesh(new THREE.BoxGeometry(...(s.length>=3?s:[.08,.08,.08]) as [number,number,number]),new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.54,i%5*.04+.38,.52)}))}
async function visual(url:string|null,kind:string,size:number[],scale:number[],i:number){let o:THREE.Object3D;try{if(url?.toLowerCase().includes('.dae'))o=(await new ColladaLoader().loadAsync(url)).scene;else if(url){const g=await new STLLoader().loadAsync(url);g.computeVertexNormals();o=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x8ca9c7}))}else o=fallback(size,i)}catch{o=fallback(size,i)}o.scale.set(...scale as [number,number,number]);return o}
async function rebuild(){if(!scene)return;if(robotGroup)scene.remove(robotGroup);objects.clear();robotGroup=new THREE.Group();const links=new Map<string,THREE.Group>();for(const link of store.scene.links){const g=new THREE.Group();g.name=link.name;g.matrixAutoUpdate=false;g.userData={entityType:'link',entityId:link.id};links.set(link.id,g);objects.set(`link:${link.id}`,g);robotGroup.add(g);for(const [i,v] of link.visuals.entries()){const o=await visual(v.resource,v.kind,v.size,v.scale,i);apply(o,v.origin.xyz,v.origin.rpy);o.traverse(x=>x.userData={entityType:v.entityType,entityId:v.id,linkId:link.id});g.add(o);objects.set(`${v.entityType}:${v.id}`,o)}}const world=new Map<string,THREE.Matrix4>();for(const root of store.scene.rootLinks)world.set(root,matrix(store.scene.rootTransform.xyz,store.scene.rootTransform.rpy));const pending=[...store.scene.joints];for(let pass=0;pass<=pending.length;pass++)for(let i=pending.length-1;i>=0;i--){const j=pending[i],pw=world.get(j.parent);if(!pw)continue;const motion=new THREE.Matrix4(),v=j.value||0;if(j.type==='prismatic')motion.makeTranslation(j.axis[0]*v,j.axis[1]*v,j.axis[2]*v);else if(j.type!=='fixed')motion.makeRotationAxis(new THREE.Vector3(...j.axis as [number,number,number]).normalize(),v);world.set(j.child,pw.clone().multiply(matrix(j.origin.xyz,j.origin.rpy)).multiply(motion));pending.splice(i,1)}links.forEach((g,id)=>g.matrix.copy(world.get(id)??new THREE.Matrix4()));scene.add(robotGroup);attachSelection()}
function selectedObject(){if(!store.selectedType||!store.selectedId)return;if(store.selectedType==='model_instance')return objects.get(`link:${store.scene.rootLinks[0]}`);if(store.selectedType==='joint'||store.selectedType==='assembly_connection'){const j=store.scene.joints.find(x=>x.id===store.selectedId);return j&&objects.get(`link:${j.child}`)}return objects.get(`${store.selectedType}:${store.selectedId}`)}
function attachSelection(){gizmo?.detach();if(outline){scene.remove(outline);outline.dispose();outline=undefined}const o=selectedObject();if(!o)return;fitView();outline=new THREE.BoxHelper(o,0x39d7ff);scene.add(outline);if(store.selectedType==='link'&&store.editSemantic==='assembly'){store.logs.push('装配编辑模式：内部 Link 已锁定；切换到运动学编辑可修改父 Joint origin');return}o.updateWorldMatrix(true,false);o.matrixWorld.decompose(proxy.position,proxy.quaternion,proxy.scale);const joint=store.selectedType==='link'?store.scene.joints.find(x=>x.child===store.selectedId):store.scene.joints.find(x=>x.id===store.selectedId);const parent=joint&&objects.get(`link:${joint.parent}`);selectedParentWorld.copy(parent?.matrixWorld??(store.selectedType==='visual'||store.selectedType==='collision'?o.parent!.matrixWorld:new THREE.Matrix4()));scene.add(proxy);gizmo.attach(proxy);if(store.transformMode==='scale'&&!['visual','collision'].includes(store.selectedType!))store.transformMode='translate'}
function targetTransform(){const local=selectedParentWorld.clone().invert().multiply(proxy.matrixWorld);const p=new THREE.Vector3(),q=new THREE.Quaternion(),s=new THREE.Vector3();local.decompose(p,q,s);const e=new THREE.Euler().setFromQuaternion(q,'XYZ');return{xyz:[p.x,p.y,p.z],rpy:[e.x,e.y,e.z],scale:[s.x,s.y,s.z]}}
function fitView(){if(!robotGroup)return;const b=new THREE.Box3().setFromObject(robotGroup);if(b.isEmpty())return;const c=b.getCenter(new THREE.Vector3()),n=b.getSize(new THREE.Vector3()).length();camera.position.copy(c).add(new THREE.Vector3(1,1,.7).normalize().multiplyScalar(n*2.2));orbit.target.copy(c);orbit.update()}
async function openPicker(){const r=await pickPath('file');if(r.path)await store.open({path:r.path})}
function click(ev:PointerEvent){if(dragging||down.distanceTo(new THREE.Vector2(ev.clientX,ev.clientY))>4)return;const rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((ev.clientX-rect.left)/rect.width*2-1,-(ev.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(robotGroup!,true).find(x=>x.object.userData.entityId);if(!hit){store.clearSelection();return}const d=hit.object.userData;if(store.selectionLevel==='geometry')store.select(d.entityType,d.entityId);else{const linkId=d.linkId||d.entityId;const link=store.scene.links.find(x=>x.id===linkId);if(link?.parentJoint&&store.scene.assemblyJoints.includes(link.parentJoint))store.select('assembly_connection',link.parentJoint);else if(store.scene.rootLinks.includes(linkId))store.select('model_instance',store.scene.robotId!);else store.select('link',linkId)}}
function key(ev:KeyboardEvent){if((ev.target as HTMLElement)?.matches('input,textarea,[contenteditable=true]'))return;const k=ev.key.toLowerCase();if((ev.ctrlKey||ev.metaKey)&&k==='z'){ev.preventDefault();ev.shiftKey?store.redo():store.undo();return}if((ev.ctrlKey||ev.metaKey)&&k==='y'){ev.preventDefault();store.redo();return}if(k==='w')store.transformMode='translate';if(k==='e')store.transformMode='rotate';if(k==='r')store.transformMode='scale';if(k==='x')store.transformSpace=store.transformSpace==='local'?'world':'local';if(k==='escape'||k==='q')store.clearSelection();if(k==='f'||k==='home')fitView()}
onMounted(()=>{scene=new THREE.Scene();scene.background=new THREE.Color(0x101923);camera=new THREE.PerspectiveCamera(42,1,.001,1000);camera.up.set(0,0,1);renderer=new THREE.WebGLRenderer({antialias:true});container.value!.appendChild(renderer.domElement);orbit=new OrbitControls(camera,renderer.domElement);gizmo=new TransformControls(camera,renderer.domElement);scene.add(gizmo.getHelper());gizmo.addEventListener('dragging-changed',e=>{dragging=Boolean(e.value);orbit.enabled=!dragging;if(!dragging&&store.selectedType&&store.selectedId)store.commit(store.selectedType as TransformTarget,store.selectedId,targetTransform()).catch(x=>store.logs.push(String(x)))});gizmo.addEventListener('objectChange',()=>{const o=selectedObject();if(o){o.matrix.copy(selectedParentWorld.clone().invert().multiply(proxy.matrixWorld));o.matrixAutoUpdate=false}});scene.add(new THREE.HemisphereLight(0xddeeff,0x1b2636,2.1),new THREE.DirectionalLight(0xffffff,2.4));const grid=new THREE.GridHelper(10,20,0x365268,0x23394c);grid.rotation.x=Math.PI/2;scene.add(grid,new THREE.AxesHelper(.5));renderer.domElement.addEventListener('pointerdown',e=>down.set(e.clientX,e.clientY));renderer.domElement.addEventListener('pointerup',click);window.addEventListener('keydown',key);const resize=()=>{const w=container.value!.clientWidth,h=container.value!.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(container.value!);resize();(function animate(){frame=requestAnimationFrame(animate);orbit.update();renderer.render(scene,camera)})()})
watch(()=>store.scene,()=>rebuild(),{deep:true});watch(()=>[store.selectedType,store.selectedId,store.editSemantic],attachSelection);watch(()=>store.transformMode,v=>{if(v==='scale'&&!['visual','collision'].includes(store.selectedType||'')){store.transformMode='translate';return}gizmo?.setMode(v)});watch(()=>store.transformSpace,v=>gizmo?.setSpace(v));watch(()=>store.snapEnabled,v=>{gizmo.setTranslationSnap(v?.01:null);gizmo.setRotationSnap(v?THREE.MathUtils.degToRad(5):null);gizmo.setScaleSnap(v?.05:null)});onBeforeUnmount(()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',key);gizmo.dispose();orbit.dispose();renderer.dispose()})
</script>
