<template>
 <section class="viewport" data-testid="robot-viewport">
  <div class="viewport-tools"><button @click="fitView">⌂</button><button @click="toggleGrid">#</button><button @click="showAxes=!showAxes">XYZ</button><span>{{store.scene.robotId || '空场景'}}</span></div>
  <div ref="container" class="canvas-host"></div>
  <div v-if="!store.scene.robotId" class="viewport-empty"><div class="empty-orbit">⌁</div><h2>三维机器人工作区</h2><p>导入 URDF、Xacro 或 MJCF 模型开始编辑</p><el-button type="primary" @click="openPicker">选择模型文件</el-button></div>
  <div class="view-cube"><b>TOP</b><span>FRONT</span><i>RIGHT</i></div>
  <div class="viewport-hint">左键旋转 · 右键平移 · 滚轮缩放</div>
 </section>
</template>
<script setup lang="ts">
import { onBeforeUnmount,onMounted,ref,watch } from 'vue'; import * as THREE from 'three'; import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js'; import {STLLoader} from 'three/examples/jsm/loaders/STLLoader.js'; import {ColladaLoader} from 'three/examples/jsm/loaders/ColladaLoader.js'; import {useEditorStore} from '@/stores/editor'; import {pickPath} from '@/api/models'
const store=useEditorStore(); const container=ref<HTMLElement>(); const showAxes=ref(true); let renderer:THREE.WebGLRenderer|undefined; let scene:THREE.Scene|undefined; let camera:THREE.PerspectiveCamera|undefined; let controls:OrbitControls|undefined; let robotGroup:THREE.Group|undefined; let frame=0
function rotationMatrix(rpy:number[]){return new THREE.Matrix4().makeRotationZ(rpy[2]||0).multiply(new THREE.Matrix4().makeRotationY(rpy[1]||0)).multiply(new THREE.Matrix4().makeRotationX(rpy[0]||0))}
function applyTransform(obj:THREE.Object3D, xyz:number[],rpy:number[]){obj.position.set(xyz[0]||0,xyz[1]||0,xyz[2]||0);obj.quaternion.setFromRotationMatrix(rotationMatrix(rpy))}
function fallbackVisual(size:number[], index:number){const dimensions=size.length>=3?size:[.08,.08,.08]; return new THREE.Mesh(new THREE.BoxGeometry(...dimensions as [number,number,number]),new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.54,index%5*.04+.38,.52),roughness:.55,metalness:.18}))}
async function createVisual(url:string|null,kind:string,size:number[],scale:number[],index:number){if(!url)return fallbackVisual(size,index); try{const lower=url.toLowerCase();if(lower.includes('.dae')){const result=await new ColladaLoader().loadAsync(url); result.scene.scale.set(...scale as [number,number,number]); return result.scene}if(lower.includes('.stl')||kind==='mesh'){const geometry=await new STLLoader().loadAsync(url); geometry.computeVertexNormals(); const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:0x8ca9c7,roughness:.58,metalness:.12})); mesh.scale.set(...scale as [number,number,number]); return mesh}}catch(error){store.logs.push(`Mesh fallback: ${String(error)}`)} return fallbackVisual(size,index)}
function transformMatrix(xyz:number[],rpy:number[]){return new THREE.Matrix4().makeTranslation(...xyz as [number,number,number]).multiply(rotationMatrix(rpy))}
async function rebuild(){if(!scene)return;if(robotGroup)scene.remove(robotGroup);robotGroup=new THREE.Group();const linkObjects=new Map<string,THREE.Group>();store.scene.links.forEach(link=>{const group=new THREE.Group();group.name=link.name;group.userData={kind:'link',id:link.id};group.matrixAutoUpdate=false;linkObjects.set(link.id,group);robotGroup!.add(group)});for(const [index,link] of store.scene.links.entries()){const group=linkObjects.get(link.id)!;for(const visual of link.visuals){const object=await createVisual(visual.resource,visual.kind,visual.size,visual.scale,index);applyTransform(object,visual.origin.xyz,visual.origin.rpy);group.add(object)}}const world=new Map<string,THREE.Matrix4>();store.scene.rootLinks.forEach(root=>world.set(root,new THREE.Matrix4()));const remaining=[...store.scene.joints];for(let pass=0;pass<=remaining.length&&remaining.length;pass++){for(let i=remaining.length-1;i>=0;i--){const joint=remaining[i],parentWorld=world.get(joint.parent);if(!parentWorld)continue;const motion=new THREE.Matrix4(),value=joint.value||0;if(joint.type==='prismatic')motion.makeTranslation(joint.axis[0]*value,joint.axis[1]*value,joint.axis[2]*value);else if(joint.type!=='fixed')motion.makeRotationAxis(new THREE.Vector3(...joint.axis as [number,number,number]).normalize(),value);world.set(joint.child,parentWorld.clone().multiply(transformMatrix(joint.origin.xyz,joint.origin.rpy)).multiply(motion));remaining.splice(i,1)}}linkObjects.forEach((group,id)=>group.matrix.copy(world.get(id)??new THREE.Matrix4()));scene.add(robotGroup);fitView()}
function fitView(){if(!robotGroup||!camera||!controls)return;const box=new THREE.Box3().setFromObject(robotGroup);if(box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length();camera.position.copy(center).add(new THREE.Vector3(1,1,.7).normalize().multiplyScalar(size*2.2));controls.target.copy(center);camera.near=Math.max(size/1000,.0001);camera.far=Math.max(size*100,100);camera.updateProjectionMatrix();controls.update()}
function toggleGrid(){if(scene){const grid=scene.getObjectByName('grid');if(grid)grid.visible=!grid.visible}}
async function openPicker(){const result=await pickPath('file');if(result.path)await store.open({path:result.path})}
onMounted(()=>{if(!container.value)return;scene=new THREE.Scene();scene.background=new THREE.Color(0x101923);camera=new THREE.PerspectiveCamera(42,1,.001,1000);camera.up.set(0,0,1);camera.position.set(2,2,1.4);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;container.value.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xddeeff,0x1b2636,2.1));const light=new THREE.DirectionalLight(0xffffff,2.4);light.position.set(4,6,3);scene.add(light);const grid=new THREE.GridHelper(10,20,0x365268,0x23394c);grid.rotation.x=Math.PI/2;grid.name='grid';scene.add(grid);scene.add(new THREE.AxesHelper(.5));const resize=()=>{if(!container.value||!renderer||!camera)return;const {clientWidth:w,clientHeight:h}=container.value;renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(container.value);resize();const animate=()=>{frame=requestAnimationFrame(animate);controls?.update();renderer?.render(scene!,camera!)};animate()})
watch(()=>store.scene,()=>rebuild(),{deep:true}); watch(showAxes,v=>{scene?.children.filter(x=>x.type==='AxesHelper').forEach(x=>x.visible=v)}); onBeforeUnmount(()=>{cancelAnimationFrame(frame);controls?.dispose();renderer?.dispose()})
</script>
