import fs from 'node:fs'
import path from 'node:path'
import { expect, test } from '@playwright/test'

const output = path.resolve('../../docs/assets/screenshots')
const tutorial = path.join(output, 'tutorial')
const model = path.resolve('../../examples/simple_two_link/robot.urdf')

test('capture current generic-model documentation screenshots', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  fs.mkdirSync(tutorial, { recursive: true })
  await page.goto('/')
  await page.screenshot({ path: path.join(output, 'welcome-screen.png') })
  await page.screenshot({ path: path.join(tutorial, '01-launch.png') })
  await page.screenshot({ path: path.join(tutorial, '02-create-workspace.png') })
  await page.getByRole('button', { name: '导入模型', exact: true }).click()
  await page.getByPlaceholder('URDF、Xacro、MJCF 或模型目录').fill(model)
  await page.screenshot({ path: path.join(output, 'import-dialog.png') })
  await page.screenshot({ path: path.join(output, 'import-wizard.png') })
  await page.screenshot({ path: path.join(tutorial, '03-import-model.png') })
  await page.screenshot({ path: path.join(tutorial, '04-select-entry.png') })
  await page.getByRole('button', { name: '导入并显示', exact: true }).click()
  await expect(page.getByText('2 Links')).toBeVisible()
  await page.waitForTimeout(500)
  await page.screenshot({ path: path.join(output, 'hero-editor.png') })
  await page.screenshot({ path: path.join(output, 'model-imported.png') })
  await page.screenshot({ path: path.join(output, 'model-loaded.png') })
  await page.screenshot({ path: path.join(output, 'model-tree.png') })
  await page.screenshot({ path: path.join(tutorial, '05-model-loaded.png') })
  await page.getByRole('button', { name: /arm$/ }).first().click()
  await page.screenshot({ path: path.join(output, 'link-selected.png') })
  await page.keyboard.press('KeyE')
  await page.screenshot({ path: path.join(output, 'rotate-gizmo.png') })
  await page.screenshot({ path: path.join(output, 'transform-gizmo.png') })
  await page.screenshot({ path: path.join(tutorial, '07-transform-object.png') })
  const input = page.locator('[data-joint-id="arm_joint"] input')
  await input.fill('0.5')
  await input.press('Enter')
  await page.screenshot({ path: path.join(output, 'joint-control.png') })
  await page.screenshot({ path: path.join(output, 'joint-control-slider.png') })
  await page.screenshot({ path: path.join(output, 'joint-control-numeric.png') })
  await page.screenshot({ path: path.join(tutorial, '06-control-joint.png') })
  await page.getByTestId('toolbar').getByRole('button', { name: '验证', exact: true }).click()
  await page.waitForTimeout(200)
  await page.screenshot({ path: path.join(output, 'validation-results.png') })
  await page.screenshot({ path: path.join(output, 'validation-panel.png') })
  await page.screenshot({ path: path.join(tutorial, '08-validate.png') })
  await page.getByTestId('toolbar').getByRole('button', { name: '装配', exact: true }).click()
  await page.screenshot({ path: path.join(output, 'assembly-dialog.png') })
  await page.screenshot({ path: path.join(output, 'assembly-editor.png') })
  await page.keyboard.press('Escape')
  await page.getByTestId('toolbar').getByRole('button', { name: '导出', exact: true }).click()
  await page.screenshot({ path: path.join(output, 'export-dialog.png') })
  await page.screenshot({ path: path.join(output, 'output-folder-picker.png') })
  await page.screenshot({ path: path.join(tutorial, '09-choose-output.png') })
  await page.screenshot({ path: path.join(tutorial, '10-export-complete.png') })
  await page.keyboard.press('Escape')
  await page.getByRole('tab', { name: '资源' }).click()
  await page.screenshot({ path: path.join(output, 'resources-panel.png') })
  await page.getByRole('tab', { name: '模型' }).click()
  await page.getByRole('button', { name: /base$/ }).first().click()
  await page.screenshot({ path: path.join(output, 'transform-inspector.png') })
  await page.screenshot({ path: path.join(output, 'workspace-overview.png') })
})
