import {mount} from '@vue/test-utils'
import {describe,expect,it,vi} from 'vitest'
import {ElMessage} from 'element-plus'
import JointValueInput from '@/components/joints/JointValueInput.vue'
const joint={id:'hinge',name:'hinge',type:'revolute',parent:'base',child:'tip',origin:{xyz:[0,0,0],rpy:[0,0,0]},axis:[0,0,1],limit:{lower:-1,upper:1},value:0}
const mountInput=(props={})=>mount(JointValueInput,{props:{joint,value:0,unit:'rad' as const,precision:3,...props}})
describe('JointValueInput',()=>{
it('keeps intermediate drafts and previews valid negative decimals',async()=>{const wrapper=mountInput();const input=wrapper.get('input');await input.trigger('focus');await input.setValue('-');expect((input.element as HTMLInputElement).value).toBe('-');expect(wrapper.emitted('preview')).toBeUndefined();await input.setValue('-.');expect((input.element as HTMLInputElement).value).toBe('-.');await input.setValue('-.5');expect(wrapper.emitted('preview')?.at(-1)).toEqual([-.5])})
it('commits on Enter and restores the edit-start value on Escape',async()=>{const wrapper=mountInput({value:.25});const input=wrapper.get('input');await input.trigger('focus');await input.setValue('-.75');await input.trigger('keydown',{key:'Enter'});expect(wrapper.emitted('commit')).toEqual([[-.75]]);await wrapper.setProps({value:-.75});await input.trigger('focus');await input.setValue('.5');await input.trigger('keydown',{key:'Escape'});expect(wrapper.emitted('commit')).toHaveLength(1);expect(wrapper.emitted('preview')?.at(-1)).toEqual([-.75])})
it('converts degrees to internal radians without rounding internal precision',async()=>{const wrapper=mountInput({unit:'deg',value:Math.PI/2});const input=wrapper.get('input');expect((input.element as HTMLInputElement).value).toBe('90.000');await input.trigger('focus');await input.setValue('45');await input.trigger('keydown',{key:'Enter'});expect(wrapper.emitted('commit')?.at(-1)?.[0]).toBeCloseTo(Math.PI/4,10)})
it('converts millimetres to metres',async()=>{const wrapper=mountInput({joint:{...joint,type:'prismatic',limit:{lower:-1,upper:1}},unit:'mm'});const input=wrapper.get('input');await input.trigger('focus');await input.setValue('125');await input.trigger('keydown',{key:'Enter'});expect(wrapper.emitted('commit')?.at(-1)).toEqual([.125])})
it('clamps with an explicit warning and supports keyboard stepping',async()=>{const warning=vi.spyOn(ElMessage,'warning').mockImplementation(()=>({} as never));const wrapper=mountInput();const input=wrapper.get('input');await input.trigger('focus');await input.setValue('4');expect(input.attributes('aria-invalid')).toBe('true');await input.trigger('keydown',{key:'Enter'});expect(wrapper.emitted('commit')?.at(-1)).toEqual([1]);expect(warning).toHaveBeenCalled();await input.trigger('focus');await input.trigger('keydown',{key:'ArrowUp'});expect(wrapper.emitted('commit')?.at(-1)).toEqual([1]);warning.mockRestore()})
})
